ctrl_interface=/var/run/wpa_supplicant
sae_pwe=2

network={
    ssid="asus_MLO"
    sae_password="Kelly2989"
    key_mgmt=SAE
    proto=RSN
    pairwise=CCMP GCMP-256
    group=CCMP GCMP-256
    ieee80211w=2
    scan_ssid=1
    scan_freq=5785 2412
}
