ctrl_interface=/var/run/wpa_supplicant

network={
    ssid="asus_SSID_6G"
    sae_password="Kelly2989"
    key_mgmt=SAE
    proto=RSN
    pairwise=CCMP GCMP-256
    group=CCMP GCMP-256
    ieee80211w=2
    scan_ssid=1
}
