ctrl_interface=/var/run/wpa_supplicant

network={
    ssid="TP-LINK_5G_Loong"
    psk="Kelly2989"
    key_mgmt=SAE
    proto=RSN
    pairwise=CCMP
    group=CCMP
    ieee80211w=2
    sae_password="Kelly2989"
}
