ctrl_interface=/var/run/wpa_supplicant

network={
    ssid="TP-LINK_5G_Loong"
    psk="YOUR_PASSWORD"
    key_mgmt=SAE
    proto=RSN
    pairwise=CCMP
    group=CCMP
    ieee80211w=2
    sae_password="YOUR_PASSWORD"
}
