ctrl_interface=/var/run/wpa_supplicant

network={
    ssid="TP-LINK_Loong"
    key_mgmt=SAE WPA-PSK WPA-PSK-SHA256
    proto=RSN
    pairwise=CCMP
    group=CCMP
    ieee80211w=1
    sae_password="Kelly2989"
    psk="Kelly2989"
}
